### ISSUE TITLE
Definição de Design Patterns

### ISSUE THREAD

**Issue by DaviQuaresma** [Film-Catalog/Documentation#1]

**Comment by gabriel-asevedo** [comment]
Em análise:
 
**Factory Method**
Quando usar: Ideal para criar objetos relacionados a filmes, como instâncias de filmes, comentários, e avaliações de forma flexível e independente.
Por que é útil: Se precisar instanciar diferentes tipos de mídia (filmes, séries, documentários), o Abstract Factory permite gerar diferentes tipos de objetos sem modificar a lógica de criação, isolando o código da lógica de instância.

**Observer**
Quando usar: Perfeito para o sistema de comentários e avaliações. Cada vez que um usuário faz uma nova avaliação ou comentário, você pode notificar outros módulos (como a interface de usuário ou o sistema de recomendação) para que reajam automaticamente.
Por que é útil: O Observer permite que o sistema reaja em tempo real a novos comentários ou avaliações, atualizando a visualização ou processando novos dados de forma automática e desacoplada.

**Decorator**
Quando usar: Caso você queira adicionar funcionalidades adicionais, como moderação de comentários, filtragem de avaliações por qualidade, ou destacar certos comentários.
Por que é útil: O Decorator permite estender o comportamento dos objetos (comentários, avaliações) de forma dinâmica, sem modificar as classes originais.

**Facade**
Quando usar: Para fornecer uma interface simples ao frontend, encapsulando a complexidade do backend.
Por que é útil: O Facade torna o sistema mais fácil de manter e menos propenso a erros, escondendo a complexidade do código backend e expondo uma interface simples para interagir com os dados do catálogo, como buscar detalhes de filmes e postar avaliações.


Mais informações:
https://drive.google.com/drive/folders/1odoPV_ZITHysTqHClmPq0UtEF4-aKoXH
